-- Create the history table
create table history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action_type text not null,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table history enable row level security;

-- Create policies
create policy "Users can see their own history" on history for select using (auth.uid() = user_id);
create policy "Users can insert their own history" on history for insert with check (auth.uid() = user_id);
